mild:
  # redisson 配置
  redisson:
    # 配置看门狗的默认超时时间为30s，这里改为 10s
    lockWatchdogTimeout: 10000
    # redis 模块key前缀
    keyPrefix: ${spring.data.redis.keyPrefix}
    # 线程池数量
    threads: 4
    # Netty线程池数量
    nettyThreads: 8
    # 单节点配置
    singleServerConfig:
      # 客户端名称
      clientName: ${spring.application.name}
      # 最小空闲连接数
      connectionMinimumIdleSize: 8
      # 连接池大小
      connectionPoolSize: 32
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
      # 设置redis 请求地址
      address: redis://${spring.data.redis.host:localhost}:${spring.data.redis.port:port}
      database: ${spring.data.redis.database:0}
  # 集群配置
    clusterServersConfig:
    # 客户端名称
      clientName: ${spring.application.name}
      # master最小空闲连接数
      masterConnectionMinimumIdleSize: 32
      # master连接池大小
      masterConnectionPoolSize: 64
      # slave最小空闲连接数
      slaveConnectionMinimumIdleSize: 32
      # slave连接池大小
      slaveConnectionPoolSize: 64
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
      # 读取模式
      readMode: "SLAVE"
      # 订阅模式
      subscriptionMode: "MASTER"
    mode: ${spring.data.redis.mode:single}