server:
  port: 8082
spring:
  application:
    name: mild-wms
  cloud:
    nacos:
      discovery:
        server-addr: 106.75.225.35:8848
        namespace: public
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.75.225.35:3306/mild?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql 执行日志
    map-underscore-to-camel-case: true # 开启自动驼峰命名规则（camel case）映射

logging:
  config: classpath:logback.xml
